// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyDeliverySystem.DataAccess;

#nullable disable

namespace PharmacyDeliverySystem.DataAcess.Migrations
{
    [DbContext(typeof(PharmacyDeliveryContext))]
    [Migration("20251117122353_AddChatMessage")]
    partial class AddChatMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("chatId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<string>("Channel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_id");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int?>("PharmacyId")
                        .HasColumnType("int")
                        .HasColumnName("Pharmacy_id");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ChatId")
                        .HasName("PK__Chat__826385AD5136740D");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("Chat", (string)null);
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.ChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__A4AE64B8BD45E9D6");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ__Customer__85FB4E385642804D")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.DeliveryRun", b =>
                {
                    b.Property<int>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RunId"));

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("RiderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("smalldatetime");

                    b.HasKey("RunId")
                        .HasName("PK__Delivery__A259D4DDCE4D248D");

                    b.ToTable("DeliveryRun", (string)null);
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("Customer_id");

                    b.Property<int?>("InvoiceNo")
                        .HasColumnType("int")
                        .HasColumnName("Invoice_No");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Payment_id");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Pdf_Url");

                    b.Property<int?>("PharmId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(20, 0)");

                    b.Property<string>("Quantity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RunId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BAF842C6638");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("PharmId");

                    b.HasIndex("RunId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.OrderItem", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("Order_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ProductId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Payment", b =>
                {
                    b.Property<string>("PayId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("METHOD");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("PayId")
                        .HasName("PK__Payment__EE8FCECF75FDE81D");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Pharmacy", b =>
                {
                    b.Property<int>("PharmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PharmId"));

                    b.Property<string>("LicenceNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PharmId")
                        .HasName("PK__Pharmacy__16360C7F04B4C542");

                    b.ToTable("Pharmacy", (string)null);
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Prescription", b =>
                {
                    b.Property<int>("PreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int>("PharmId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PreId")
                        .HasName("PK__Prescrip__7024CEC96EDAC11B");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PharmId");

                    b.ToTable("Prescription", (string)null);
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Product", b =>
                {
                    b.Property<int>("ProId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProId"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Brand")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Dosage")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PharmId")
                        .HasColumnType("int");

                    b.Property<string>("VatRate")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("VAT_Rate");

                    b.HasKey("ProId")
                        .HasName("PK__PRODUCTS__62029590CEE37925");

                    b.HasIndex("PharmId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.QrConfirmation", b =>
                {
                    b.Property<int>("QR_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QR_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QR_Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("smalldatetime");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<int?>("DeliveryRunId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EXP_date")
                        .HasColumnType("datetime")
                        .HasColumnName("EXP_date");

                    b.Property<string>("ScannedBy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("QR_Id")
                        .HasName("PK__QRConfir__7491345D2085C5B7");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryRunId");

                    b.ToTable("QRConfirmation", (string)null);
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Refund", b =>
                {
                    b.Property<int>("RefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefId"));

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("PayId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RefId")
                        .HasName("PK__Refund__2D2A2CF13D79525D");

                    b.HasIndex("PayId");

                    b.ToTable("Refund", (string)null);
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Return", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnId"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ReturnId")
                        .HasName("PK_Returnn_F445E9A86A4CD3B7");

                    b.HasIndex("OrderId");

                    b.ToTable("Return", (string)null);
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Chat", b =>
                {
                    b.HasOne("PharmacyDeliverySystem.Models.Customer", "Customer")
                        .WithMany("Chats")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Chat_Customer");

                    b.HasOne("PharmacyDeliverySystem.Models.Order", "Order")
                        .WithMany("Chats")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Chat__OrderID__5EBF139D");

                    b.HasOne("PharmacyDeliverySystem.Models.Pharmacy", "Pharmacy")
                        .WithMany("Chats")
                        .HasForeignKey("PharmacyId")
                        .HasConstraintName("FK_Chat_Pharmacy");

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.ChatMessage", b =>
                {
                    b.HasOne("PharmacyDeliverySystem.Models.Chat", "Chat")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Order", b =>
                {
                    b.HasOne("PharmacyDeliverySystem.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Orders_Customer");

                    b.HasOne("PharmacyDeliverySystem.Models.Payment", "Payment")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK_Orders_Payment");

                    b.HasOne("PharmacyDeliverySystem.Models.Pharmacy", "Pharm")
                        .WithMany("Orders")
                        .HasForeignKey("PharmId")
                        .HasConstraintName("FK__Orders__PharmId__4D94879B");

                    b.HasOne("PharmacyDeliverySystem.Models.DeliveryRun", "Run")
                        .WithMany("Orders")
                        .HasForeignKey("RunId")
                        .HasConstraintName("FK__Orders__RunId__4E88ABD4");

                    b.Navigation("Customer");

                    b.Navigation("Payment");

                    b.Navigation("Pharm");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.OrderItem", b =>
                {
                    b.HasOne("PharmacyDeliverySystem.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Prescription", b =>
                {
                    b.HasOne("PharmacyDeliverySystem.Models.Customer", "Customer")
                        .WithMany("Prescriptions")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Prescript__Custo__5165187F");

                    b.HasOne("PharmacyDeliverySystem.Models.Order", "Order")
                        .WithMany("Prescriptions")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Prescript__Order__534D60F1");

                    b.HasOne("PharmacyDeliverySystem.Models.Pharmacy", "Pharm")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PharmId")
                        .IsRequired()
                        .HasConstraintName("FK__Prescript__Pharm__52593CB8");

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("Pharm");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Product", b =>
                {
                    b.HasOne("PharmacyDeliverySystem.Models.Pharmacy", "Pharm")
                        .WithMany("Products")
                        .HasForeignKey("PharmId")
                        .HasConstraintName("FK__PRODUCTS__PharmI__59063A47");

                    b.Navigation("Pharm");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.QrConfirmation", b =>
                {
                    b.HasOne("PharmacyDeliverySystem.Models.Customer", "Customer")
                        .WithMany("QrConfirmations")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__QRConfirm__Custo__6C190EBB");

                    b.HasOne("PharmacyDeliverySystem.Models.DeliveryRun", "DeliveryRun")
                        .WithMany("QrConfirmations")
                        .HasForeignKey("DeliveryRunId")
                        .HasConstraintName("FK_QRConfirmation_DeliveryRun");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryRun");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Refund", b =>
                {
                    b.HasOne("PharmacyDeliverySystem.Models.Payment", "Pay")
                        .WithMany("Refunds")
                        .HasForeignKey("PayId")
                        .HasConstraintName("FK__Refund__PayId__619B8048");

                    b.Navigation("Pay");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Return", b =>
                {
                    b.HasOne("PharmacyDeliverySystem.Models.Order", "Order")
                        .WithMany("Returns")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Chat", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Customer", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Orders");

                    b.Navigation("Prescriptions");

                    b.Navigation("QrConfirmations");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.DeliveryRun", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("QrConfirmations");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Order", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("OrderItems");

                    b.Navigation("Prescriptions");

                    b.Navigation("Returns");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Payment", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("PharmacyDeliverySystem.Models.Pharmacy", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Orders");

                    b.Navigation("Prescriptions");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
